<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net7.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="DTOs\**" />
	  <Content Remove="DTOs\**" />
	  <EmbeddedResource Remove="DTOs\**" />
	  <None Remove="DTOs\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Google.Apis.Auth" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
		<PackageReference Include="Microsoft.Data.SqlClient" />
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
		<PackageReference Include="Swashbuckle.AspNetCore" />
		<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Google" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
		<PackageReference Include="Swashbuckle.AspNetCore.Newtonsoft" />
		
		<!-- Prometheus Metrics -->
		<PackageReference Include="prometheus-net.AspNetCore" Version="8.2.1" />
		
		<!-- OpenTelemetry Tracing -->
		<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.9.0" />
		<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.9.0" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.9.0" />
		<PackageReference Include="OpenTelemetry.Instrumentation.SqlClient" Version="1.9.0-beta.1" />
		<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.9.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\FTM.Application\FTM.Application.csproj" />
		<ProjectReference Include="..\FTM.Infrastructure\FTM.Infrastructure.csproj" />
	</ItemGroup>

</Project>
